---
- name: Set prepd environment variables
  include_role:
    name: prepd/project

- include_role:
    name: prepd/utils
    tasks_from: debug

# TODO: What about this?
# - name: Ensure data and crendentials directories exist
#   file:
#     path: '{{ project_data_dir }}/{{ item }}'
#     state: directory
#   with_items: [credentials, data, vault]
# 
# - name: Ensure ssh keys directory exists
#   file:
#     path: '{{ ssh_dir }}'
#     state: directory
#     line: 'vault_password_file = {{ vault_dir }}/password.txt'

# TODO: Work this out
- name: Ensure each inventory directory exists
  file:
    path: '{{ playbook_dir }}/inventory/{{ item }}'
    state: directory
  with_items: "{{ ['local'] + setup_inventories }}"

- name: Ensure each group_vars directory exists
  file:
    path: '{{ playbook_dir }}/group_vars/{{ item }}'
    state: directory
  with_items: "{{ ['local'] + setup_inventories }}"

- name: Template the inventory roles
  template:
    src: inventory-roles.j2
    dest: '{{ playbook_dir }}/inventory/roles'

- name: Softlink the roles file into each environment
  file:
    src: '../roles'
    dest: '{{ playbook_dir }}/inventory/{{ item }}/roles'
    state: link
  with_items: "{{ ['local'] + setup_inventories }}"

- name: One time template the hosts file for each environment
  template:
    src: inventory-hosts.j2
    dest: '{{ playbook_dir }}/inventory/{{ item }}/hosts'
    force: no
  with_items: '{{ setup_inventories }}'


# NOTE: Not sure if this is really needed; Ansible has a new strategy for multiple environment vault files
# - name: One time create vault password file for each environment
#   copy:
#     force: no
#     content: '{{ 1000000000000 | random | to_uuid }}'
#     dest: '{{ vault_dir }}/{{ item }}.txt'
#   with_items: '{{ setup_inventories }}'

#
# NOTE: Replace with functionality specific playbooks that target different environments using roles
# - name: Template a playbook for each role
#   template:
#     src: role-playbook.yml.j2
#     dest: '{{ playbook_dir }}/{{ item }}s.yml'
#     mode: 0755
#     force: no
#   with_items: '{{ setup_roles }}'
