---
# NOTE: List repoistories in registry: curl -X GET http://{{ spec.cluster_host }}:{{ spec.cluster_registry_port }}/v2/_catalog
base_spec:
  cluster_host: node1
  cluster_registry_port: 30005
  cluster_grafana_port: 30006
  charts:
    - registry

spec: '{{ base_spec | combine(role_spec, recursive=True) }}'
