---
# NOTE: Not in use right now
# NOTE: $AWS_PROFILE is used to specify account to access the tf bucket
# The tfvars file still needs to be used to specifiy different AWS accounts for the acutal plan apply
- name: Ensure the terraform credentials directory exists
  file:
    path: '{{ tf_creds_dir }}'
    state: directory

- name: Generate tfvars for each terraform credential
  template:
    src: terraform.tfvars.j2
    dest: "{{ tf_creds_dir }}/{{ item.key.split('_')[-1] }}.tfvars"
  with_dict: '{{ aws_keys }}'
