---
- include_tasks: install.yml
  when: task == 'setup'

- include_role:
    name: terraplate/provider-resources
  vars:
    provider: '{{ item }}'
  with_items: '{{ terraform_resource_providers }}'
  when: task == 'resources'

- name: Setup lib or app directory for service
  include_role:
    name: terraplate/setup
  when: task == 'blueprints' or task == 'deploy'
