---
- name: Load credentials
  include_role:
    name: prepd/credentials
  vars:
    credentials_action: load

- name: Template the AWS credentials file
  blockinfile:
    create: yes
    dest: '{{ credentials_write_aws_file }}'
    marker: '# {mark} {{ credentials_write_aws_context }}-{{ aws.key }}'
    block: |
      [{{ (credentials_write_aws_context + '-' + aws.key) | replace('_', '-') }}]
      aws_access_key_id = {{ aws.value.aws_access_key_id }}
      aws_secret_access_key = {{ aws.value.aws_secret_access_key }}
  with_dict: '{{ prepd_credentials.aws }}'
  loop_control:
    loop_var: aws
  when: prepd_credentials.aws is defined

- name: Ensure directory exists
  file:
    path: '{{ credentials_write_terraform_dir }}'
    state: '{{ item }}'
  with_items: [absent, directory]

- name: Template GitHub credentials as tfvars
  blockinfile:
    create: yes
    dest: '{{ credentials_write_terraform_dir }}/{{ credentials_write_terraform_github }}'
    marker: '# {mark} {{ github.key }}'
    block: |
      provider_github_token = "{{ github.value.token }}"
      provider_github_organization = "{{ github.value.organization }}"
  with_dict: '{{ prepd_credentials.github }}'
  loop_control:
    loop_var: github
  when: prepd_credentials.github is defined
