---
- name: Download the inventory script into playbook_dir/inventory directory
  get_url:
    url: 'https://raw.githubusercontent.com/ansible/ansible/stable-{{ ansible_version.major }}.{{ ansible_version.minor }}/contrib/inventory/ec2.py'
    dest: '{{ spec.base_inventory_dir }}/ec2.py'
    mode: u=rwx,g=r,o=r

- name: Softlink the inventory script into the environment
  file:
    src: '../ec2.py'
    dest: '{{ spec.inventory_dir }}/ec2.py'
    state: link

- name: Template an ini file for each environment
  template:
    src: ec2.ini.j2
    dest: '{{ spec.inventory_dir }}/ec2.ini'
