---
- name: Set prepd developer vars
  include_role:
    name: prepd/developer

- name: Get the full hostname of the machine
  command: hostname -f
  register: hostname
  changed_when: false

- name: Set the prepd variables
  set_fact:
    prepd_run_context: machine
    prepd_machines_dir: '{{ prepd_dir }}/config/machines'
    prepd_machine_name: '{{ hostname.stdout.split(".")[1] }}'
    prepd_projects_dir: '{{ prepd_dir }}/config/projects'
- set_fact:
    prepd_machine_dir: '{{ prepd_machines_dir }}/{{ prepd_machine_name }}'

- name: Include machine variables
  include_vars:
    file: '{{ prepd_machine_dir }}/vars/setup.yml'
    name: prepd_machine

- name: Set prepd_machine_project_names
  set_fact:
    prepd_machine_project_names: "{{ prepd_machine.data.projects | map(attribute='name') | list }}"
