# Writes the value of aws_cli_credentials to aws_cli_dir/aws_cli_credentials_file (default: ~/.aws/credentials)
# TODO: Read and parse an AWS CSV file
---
- name: Ensure the ~/.aws directory exists
  file:
    dest: '{{ aws_cli_dir }}'
    state: directory

- name: Template the credentials file
  blockinfile:
    create: yes
    dest: '{{ aws_cli_dir }}/{{ aws_cli_credentials_file }}'
    marker: '# {mark} {{ aws_cli_context }}'
    block: |
      {% for key, values in aws_cli_credentials.iteritems() %}
      [{{ aws_cli_context | replace('_', '-') }}-{{ key | replace('_', '-') }}]
      aws_access_key_id = {{ values.aws_access_key_id }}
      aws_secret_access_key = {{ values.aws_secret_access_key }}

      {% endfor %}
