---
- set_fact:
    role: "{{ rabbitmq|combine(project.rabbitmq|default({})) }}"

- name: Install Debian packages
  apt: name={{ item }} state=present
  become: yes
  with_items: [rabbitmq-server]
  when: ansible_distribution == 'Debian'

- name: Configure rabbitmq vhosts
  rabbitmq_vhost:
    name: '{{ item }}'
  with_items: '{{ project.environments }}'
  become: yes

- name: Configure rabbitmq user and vhosts
  rabbitmq_user: user={{ role.username }}
                 password={{ role.password }}
                 vhost={{ item }}
                 read_priv=.*
                 write_priv=.*
                 configure_priv=.*
  with_items: '{{ project.environments }}'
  become: yes
