---
- name: Enable etcd
  command: systemctl enable etcd
  become: yes

- name: Reload etcd
  command: systemctl daemon-reload
  become: yes

- name: Restart etcd
  service:
    name: etcd
    state: restarted
    enabled: yes
  become: yes

  # - name: Wait for etcd listening
  #   wait_for: port=2379 timeout=60
  # 
  # - name: Verify etcd cluster health
  #   shell: etcdctl --ca-file=/etc/etcd/ca.pem cluster-health
  #   register: cmd_result
  #   until: cmd_result.stdout.find("cluster is healthy") != -1
  #   retries: 5
  #   delay: 5
