---
- name: Install Debian packages
  apt:
    name: '{{ package }}'
    state: present
    update_cache: yes
    cache_valid_time: '{{ cache_valid_time | default(86400) }}'
  become: yes
  with_items: [nginx]
  loop_control:
    loop_var: package
