---
- name: Ensure /srv/www directory exists
  file:
    path: /srv/www
    state: directory
    owner: www-data
  become: yes

- name: Configure nginx to respond to ELB health checks
  copy:
    src: index.html
    dest: /srv/www/index.html
    mode: 0644
    owner: www-data
  become: yes
  when: nginx_elb_healthcheck is defined
