---
- include_vars:
    file: '{{ ansible_os_family }}.yml'

- name: Install nginx
  include_tasks: '{{ ansible_distribution }}.yml'

- name: 'Create {{ spec.sites_dir }}'
  file:
    path: '{{ spec.sites_dir }}'
    state: directory
    owner: '{{ spec.owner }}'
  become: yes

- name: Configure nginx sites
  include_tasks: site.yml
  notify: Restart Nginx
  with_dict: '{{ spec.sites }}'
  loop_control:
    loop_var: site

- name: Configure nginx to respond to health checks
  import_tasks: health-check.yml
  become: yes
  notify: Restart Nginx
  when: spec.healthcheck
