---
- name: Configure an nginx site
  template:
    src: site.conf.j2
    dest: '{{ spec.config_dir }}/{{ site.key }}.conf'
    owner: '{{ spec.owner }}'
    mode: 0644
  become: yes

- file:
    src: '{{ spec.config_dir }}/{{ site.key }}.conf'
    path: '/etc/nginx/sites-enabled/{{ site.key }}.conf'
    state: link
  become: yes
  when: ansible_distribution == 'Debian'
