---
- debug:
    var: '{{ debug_item }}'
    verbosity: 1
  with_items: [key, key_and_file]
  loop_control:
    loop_var: debug_item

- name: Convert the CSV contents to YAML
  template:
    src: credentials.yml.j2
    dest: "{{ aws_credentials_dir }}/{{ aws_cli_context }}/vault/credentials/aws/{{ key }}.yml"

- name: Encrypt the yaml file
  command: "ansible-vault encrypt {{ item.path | regex_replace('csv$', 'yml') }}"

- name: Delete the csv file
  file:
    path: '{{ item.path }}'
    state: absent
