---
- include_role:
    name: prepd/python

- name: Install awscli
  pip:
    name: awscli
    state: present
  become: yes

- name: Ensure the ~/.aws directory exists
  file:
    dest: '{{ aws_cli_dir }}'
    state: directory

- debug:
    var: aws_credentials
    verbosity: 1

- include_role:
    name: prepd/credentials
  vars:
    credentials_provider: aws
    credentials_project_names: '{{ project_names }}'
    credentials_src_dir: '{{ aws_credentials_dir }}'
    credentials_src_pattern: csv
