---
- include_role:
    name: prepd/python

- name: Install awscli
  pip:
    name: awscli
    state: present
  become: yes

- name: Ensure the ~/.aws directory exists
  file:
    dest: '{{ aws_cli_dir }}'
    state: directory

- debug:
    var: project_names

- include_tasks: project.yml
  with_items: '{{ project_names }}'
  loop_control:
    loop_var: aws_cli_context
