---
- name: Get a list of raw credential csv files in the project's vault
  find:
    paths: '{{ aws_credentials_dir }}/{{ aws_cli_context }}/vault/credentials/aws'
    patterns: '*.csv'
  register: csv_files

- name: Convert all csv files to YAML
  include_tasks: csv-credentials-to-yaml.yml key="{{ item.path.split('/')[-1].split('.')[0] }}" key_and_file="{{ item.path.split('/')[-1].split('.')[0] }} file={{ item.path }}"
  with_items: '{{ csv_files.files }}'

- name: Get a list of YAML files in the project's vault
  find:
    paths: '{{ aws_credentials_dir }}/{{ aws_cli_context }}/vault/credentials/aws'
    patterns: '*.yml'
  register: yml_files

- debug:
    var: yml_files
    verbosity: 1

- name: Write the YAML contents to ~/.aws/credentials
  include_tasks: yaml-credentials-to-aws.yml key="{{ item.path.split('/')[-1].split('.')[0] }}"
  with_items: '{{ yml_files.files }}'
