# These tasks are called from prepd/credentials/tasks/source-credentials-to-yaml.yml
---
- set_fact:
    aws_access_key_id: "{{ contents.split('\r\n')[1].split(',')[0] }}"
    aws_secret_access_key: "{{ contents.split('\r\n')[1].split(',')[1] }}"

- debug:
    var: '{{ debug_item }}'
    verbosity: 0
  with_items: [dest, contents, aws_access_key_id, aws_access_key_id, aws_cli_dir, aws_cli_credentials_file, context, key]
  loop_control:
    loop_var: debug_item

- name: Convert the CSV contents to YAML
  template:
    src: yaml-credentials.yml.j2
    dest: '{{ dest }}'

- name: Template the credentials file
  blockinfile:
    create: yes
    dest: '{{ aws_cli_dir }}/{{ aws_cli_credentials_file }}'
    marker: '# {mark} {{ context }}-{{ key }}'
    block: |
      [{{ (context + '-' + key) | replace('_', '-') }}]
      aws_access_key_id = {{ aws_access_key_id }}
      aws_secret_access_key = {{ aws_secret_access_key }}

