---
- name: Install Debian packages
  apt:
    name: '{{ package }}'
  with_items: [rake, git, zsh, vim-nox]
  loop_control:
    loop_var: package
  become: yes
  when: ansible_pkg_mgr == 'apt'

# TODO: on mac install vim with lua support for neocomplete
#  brew install vim --with-lua

- name: Download Yadr
  get_url:
    url: https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh
    dest: /tmp/yadr_install.sh
    mode: 0755

- name: Install Yadr
  command: bash -c 'echo yes | /tmp/yadr_install.sh'

- name: Remove the installation script
  file:
    path: /tmp/yadr_install.sh
    state: absent

- name: Update zprofile
  blockinfile:
    create: yes
    dest: '{{ ansible_env.HOME }}/.zprofile'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (yadr)'
    block: |
      export LC_CTYPE='en_US.UTF-8'
      export LANG='en_US.UTF-8'
      export LANGUAGE='en_US.UTF-8'
  when: false # ansible_distribution == 'Debian'
