---
- name: Install Debian packages
  apt:
    name: '{{ item }}'
  with_items: [rake, git, zsh, vim-nox]
  become: yes
  when: ansible_pkg_mgr == 'apt'

- name: Check if YADR is installed
  stat: path={{ ansible_env.HOME }}/.yadr
  register: yadr_dir

- name: Download YADR
  get_url:
    url: https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh
    dest: /tmp/yadr_install.sh
    mode: 0755
  when: yadr_dir.stat.exists == false

- name: Install YADR
  command: bash -c 'echo yes | /tmp/yadr_install.sh'
  when: yadr_dir.stat.exists == false

- name: Set the user shell to zsh
  user:
    name: '{{ ansible_user }}'
    shell: /bin/zsh
  become: yes
  when: ansible_distribution == 'Debian'

- name: Update zprofile
  blockinfile:
    create: yes
    dest: '{{ ansible_env.HOME }}/.zprofile'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (yadr)'
    block: |
      export LC_CTYPE='en_US.UTF-8'
      export LANG='en_US.UTF-8'
      export LANGUAGE='en_US.UTF-8'
  when: ansible_distribution == 'Debian'

- name: Copy home directory hidden files
  copy:
    src: 'home/{{ item }}'
    dest: '{{ ansible_env.HOME }}/.{{ item }}'
  with_items:
    - tmux.conf.user
    - vimrc.after
    - yadr/ctags/ctags

# TODO: move the git alias to Git role if ever there is one
- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (yadr)'
    block: |
      alias ave='ansible-vault edit'
      alias gsu='git submodule update --remote --merge'
      alias du='du -csh *'

- name: Remove bogus line from .vimrc
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.vimrc'
    state: absent
    regexp: "^set list listchars"
