---
- name: Register YADR installation state
  stat:
    path: '{{ ansible_env.HOME }}/.yadr'
  register: yadr_dir

- include: 'install.yml'
  when: yadr_dir.stat.exists == false

- include: 'update.yml'
  when: yadr_dir.stat.exists == true
