---
- name: Register YADR installation state
  stat:
    path: '{{ ansible_env.HOME }}/.yadr'
  register: yadr_dir

- include_tasks: install.yml
  when: yadr_dir.stat.exists == false

#- include_tasks: 'update.yml'
#  when: yadr_dir.stat.exists == true

- name: Copy home directory hidden files
  copy:
    src: 'home/{{ item }}'
    dest: '{{ ansible_env.HOME }}/.{{ item }}'
  with_items:
    - tmux.conf.user
    - vimrc.after
    - yadr/ctags/ctags

# TODO: Test if this will work with prepd/aliases role b/c it is not known if the user's shell is zsh yet?
- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (yadr)'
    block: |
      alias ave='ansible-vault edit'
      alias avc='ansible-vault create'
      alias du='du -csh *'

      # Edit and source this file
      alias via='vi ~/.zsh.after/aliases.zsh; source ~/.zsh.after/aliases.zsh'

### git creds
- name: Write git user info to ~/.gitconfig.user
  template:
    src: gitconfig.user.j2
    dest: '{{ ansible_env.HOME }}/.gitconfig.user'
  when: git_user is defined

- name: Remove bogus line from .vimrc
  lineinfile:
    path: '{{ ansible_env.HOME }}/.vimrc'
    state: absent
    regexp: "^set list listchars"

- name: Remove config that causes vim to suspend
  lineinfile:
    path: '{{ ansible_env.HOME }}/.yadr/vim/settings/path.vim'
    line: 'set shell=bash\ -i'
    state: absent
  when: ansible_distribution == 'Debian'
