---
- name: "Create softlinks to the application's source .env file"
  file:
    path: '{{ config.directory }}/{{ item.name }}/.env'
    src: '{{ config.directory }}/.env'
    state: link
  with_items: '{{ config.ruby.rails_apps }}'

- name: Create softlinks to .env file in spec/dummy for engines
  file:
    path: '{{ config.directory }}/{{ item.name }}/spec/dummy/.env'
    src: '{{ config.directory }}/.env'
    state: link
  with_items: '{{ config.ruby.rails_apps }}'
  when: item.engine is defined and item.engine

- name: Configure repo as a local source in ~/.bundle/config
  lineinfile:
    dest: ~/.bundle/config
    state: present
    line: 'BUNDLE_LOCAL__{{ item.name.replace("-", "_").upper() }}: "{{ config.directory }}/{{ item.name }}"'
  with_items: '{{ config.source_repos }}'
  when: item.local is defined and item.local

- name: Run bundle on rails applications
  shell: . /etc/profile && ~/.rbenv/shims/bundle
  args:
    chdir: '{{ config.directory }}/{{ item.name }}'
  with_items: '{{ config.ruby.rails_apps }}'
  when: item.build is defined and item.build

# - name: Run database migrations on engine build applications
#   shell: . /etc/profile && ~/.rbenv/shims/bundle exec rake {{ 'app:' if item.engine is defined else '' }}db:migrate {{ 'app:' if item.engine is defined else '' }}db:test:prepare
#   args:
#     chdir: '{{ config.directory }}/{{ item.name }}'
#   with_items: '{{ config.ruby.rails_apps }}'
#   when: item.build is defined

- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (project-setup)'
    block: |
      alias adc='spring rake app:db:clean'
      alias adm='spring rake app:db:migrate'
      alias admc='spring rake app:db:migrate:clean'
      alias admcs='spring rake app:db:migrate:seed'
      alias ads='spring rake app:db:seed'
      alias adsc='spring rake app:db:seed:clean'
      alias adsct='SEED_TENANT=true spring rake app:db:seed:clean'
      alias adtp='spring rake app:db:test:prepare'

      alias beg='bundle exec guard'

      alias dc='spring rake db:clean'
      alias dm='spring rake db:migrate'
      alias dmc='spring rake db:migrate:clean'
      alias dmcs='spring rake db:migrate:seed'
      alias dsc='spring rake db:seed:clean'
      alias dtp='spring rake db:test:prepare'

      alias fs='foreman start -e <()'

      alias ggpl='spring stop; git checkout Gemfile.lock; git pull'

      alias pss='ps -ef|grep spring'

      alias rc='spring rails console'
      alias rg='spring rails generate'
      alias rgjc='spring rails generate jsonapi:controller'
      alias rgjr='spring rails generate jsonapi:resource'
      alias rgm='spring rails generate model'
      alias rk='spring rake'
      alias rkd='RAILS_ENV=test spring rake docs:generate'
      alias rs='spring rspec'

      alias src='spring stop; rc'
      alias ss='spring stop'
