---

          # NOTE: For some reason, updated gems from git are not included unless this is run twice
          #     system_run('bundle package --all')
          #         system_run('bundle package --all')
          #             system_run("docker build -t quay.io/getperx/#{project} .")
          #               end
- name: 'Prepare {{ image_directory }} projects for building docker images'
  shell: . /etc/profile && rm -f Gemfile.lock && ~/.rbenv/shims/bundle package --all && ~/.rbenv/shims/bundle package --all > /tmp/prepared_{{ item.name }}
  args:
    chdir: '{{ image_directory }}/{{ item.name }}{{ image_directory_suffix }}'
    creates: '/tmp/prepare_{{ item.name }}'
  with_items: '{{ proj.group.projects }}'
  when: item.image is defined
