---
- set_fact:
    source_directory: '{{ proj.group.source_directory }}'
    image_directory: '{{ proj.group.image_directory }}'
    image_directory_suffix: '{{ proj.group.image_directory_suffix }}'
  tags: always

# See: http://docs.ansible.com/ansible/docker_image_module.html
- name: 'Build {{ image_directory }} docker images'
  docker_image:
    path: '{{ image_directory }}/{{ item.name }}{{ image_directory_suffix }}'
    name: '{{ project.docker.repository }}/{{ item.name }}'
    state: present
  with_items: '{{ proj.group.projects }}'
  when: item.image is defined
  tags: build-images
