# NOTE: This playbook assumes a Debian based system
---
- name: Include python role
  include_role:
    name: prepd/python

- name: Install dependencies
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items: [apt-transport-https, ca-certificates, wget, software-properties-common, bash-completion]

- name: Install docker debian gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repo to apt
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian stretch stable'

- name: Install docker
  apt:
    name: docker-ce
    state: present

- name: Add ansible_user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

- name: Make sure docker service is running
  systemd:
    name: docker
    state: started

- name: Install docker python libs
  pip:
    name: '{{ item }}'
    state: present
  with_items: [docker, docker-compose]

- name: Install bash completion for docker
  get_url:
    url: https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/docker-machine.bash
    dest: /etc/bash_completion.d/docker
    mode: 0644
