---
- include: 'install.yml'
  become: yes

- name: Get the user shell
  command: echo $SHELL
  register: shell

- set_fact:
    aliases_file: { '/bin/zsh': '.zsh.after/aliases.zsh', '/bin/bash': '.bash_aliases' }

- name: Insert aliases
  blockinfile:
    create: yes
    dest: "{{ ansible_env.HOME }}/{{ aliases_file[shell.stdout] | default('/tmp/test') }}"
    marker: '# {mark} ANSIBLE MANAGED BLOCK (docker)'
    block: |
      alias di='docker images'
      alias dps='docker ps'
      drma() {
        docker rm $(docker ps -a -q)
      }
