---
- name: Check if docker exists
  stat:
    path: /usr/bin/docker
  register: binary

- import_tasks: install.yml
  become: yes
  when: binary.stat.exists == false

- include_role:
    name: prepd/aliases
  vars:
    aliases_marker: docker
    aliases_block: |
      alias di='docker images'
      alias drmi='docker rmi'
      alias dps='docker ps'
      alias dpsa='docker ps -a'
      drma() {
        docker stop $(docker ps -a -q)
        docker rm $(docker ps -a -q)
      }
      alias dup='docker-compose up'
