# TODO: update prepd-gem so that it writes machine projects to:
# config/machines/frank/vars/setup.yml

# TODO: Stripping off the dir from ~/config/projects/a/client/path/to/project
# gives 'a/client/path/to' which is where on the VM that the path
# for the project should be set, relative to ~/projects or whatever project_dir is set to

# TODO: rm setup/templates/developer.yml.j2 after confirming aws and github roles work
---
- debug:
    var: data # machine
    verbosity: 1

# - include_role:
#     name: prepd/common

- name: Configure the machine projects as defined in the machines vars/setup.yml file
  include_role:
    name: prepd/setup
    tasks_from: project
  with_items: '{{ data.projects }}'
  loop_control:
    loop_var: project_name
  when: data.projects is defined
