---
- name: Set prepd environment variables
  include_role:
    name: prepd/machine

- include_role:
    name: prepd/utils
    tasks_from: debug

# TODO: Developer role is intended to be a one-off setup per machine
# so common should probably go there
# however the timezone needs to be able to be set per machine so ???
# - include_role:
#     name: prepd/common
#   vars:
#     machine_time_zone: '{{ prepd_developer.machine_time_zone }}'

- name: Configure the machine projects as defined in the machines vars/setup.yml file
  include_tasks: project.yml
  with_items: '{{ prepd_machine.data.projects }}'
  loop_control:
    loop_var: project_name
  when: false # prepd_machine.data.projects is defined

- name: Check if custom machine tasks file exist
  stat:
    path: '{{ prepd_machine_dir }}/setup.yml'
  register: machine_setup_file

- name: Include custom machine tasks
  include_tasks: '{{ prepd_machine_dir }}/setup.yml'
  when: machine_setup_file.stat.exists
