---
# - debug: var=tfg_vars
# - debug: var=tfg_defaults
# - debug: var=tfg_props
# - debug: var=tfg
# - debug: var=roles

- set_fact:
    task_name: config

- include_role:
    name: prepd/common
  vars:
    machine_env: '{{ machine }}'

- include_role:
    name: 'prepd/{{ role_item }}'
    tasks_from: config
  vars:
    properties: '{{ role_properties[role_item] | default({}) }}'
  with_items: '{{ roles }}'
  loop_control:
    loop_var: role_item
