---
- name: Install google-chrome apt repo
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    state: present
  become: yes
  when: "'google-chrome-stable' in extra_items.debian"

- apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  with_items: '{{ extra_items.debian }}'
