# NOTE: the order of the roles is important: virtualbox is first b/c it will fail on mac the first time
---
- include_role:
    name: prepd/machine-config
  vars:
    role_spec: {}

- include_role:
    name: prepd/virtualbox

- include_role:
    name: prepd/vagrant/setup

- include_role:
    name: prepd/prepd-tools
  vars:
    role_spec: {}

- include_tasks: '{{ ansible_os_family | lower }}.yml'
