---
- name: Create softlinks to a tmuxinator file from an external project
  file:
    path: '{{ ansible_env.HOME }}/.tmuxinator/{{ item.name }}'
    src: '{{ item.src }}'
    state: link
  with_items: '{{ files }}'
