---
- name: Install Debian packages
  apt:
    name: tmux
    state: present
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  when: ansible_distribution == 'Debian'

- name: Install tmuxinator gem
  gem:
    name: tmuxinator
    state: present

- name: Create .tmuxinator directory in home
  file:
    path: '{{ tmuxinator_dir }}'
    state: directory
    mode: 0755

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: tmuxinator
    aliases_block: |
      alias tl='tmux list-sessions'
      alias ta='tmux a -dt $1'
      alias mux='tmuxinator'

- include_tasks: session.yml
