---
- name: Install Debian packages
  apt:
    name: tmux
    state: present
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  when: ansible_distribution == 'Debian'

- name: Install tmuxinator gem
  gem:
    name: tmuxinator
    state: present

- name: Create .tmuxinator directory in home
  file:
    path: '{{ tmuxinator_dir }}'
    state: directory
    mode: 0755

- name: Insert aliases
  blockinfile:
    create: yes
    dest: '{{ machine_aliases_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (tmuxinator)'
    block: |
      # Shortcuts for TMux
      alias tl='tmux list-sessions'
      alias ta='tmux a -dt $1'
      alias mux='tmuxinator'
  when: machine_shell == 'zsh'

- include_tasks: session.yml
