---
- name: Create .tmuxinator directory in home
  file:
    path: '{{ ansible_env.HOME }}/.tmuxinator'
    state: directory
    mode: 0755

- name: Copy prepd.yml
  copy:
    src: prepd.yml
    dest: '{{ ansible_env.HOME }}/.tmuxinator/prepd.yml'

- name: Copy template files
  template:
    dest: '{{ ansible_env.HOME }}/.tmuxinator/{{ item }}.yml'
    src: lego.j2
  with_items: '{{ projects }}'

- name: Create softlinks to a tmuxinator file from an external project
  file:
    dest: '{{ ansible_env.HOME }}/.tmuxinator/{{ item.name }}'
    src: '{{ item.src }}'
    state: link
  with_items: '{{ files }}'

- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (tmuxinator)'
    block: |
      alias mux='tmuxinator'
