---
- name: Create softlinks to a tmuxinator file from an external project
  file:
    path: '{{ tmuxinator_dir }}/{{ item.name }}.yml'
    src: '{{ item.src }}'
    state: link
  with_items: '{{ tmuxinator_sessions }}'
