---
- name: Create the project directory
  file:
    path: '{{ project.directory }}'
    state: directory

- name: Checkout the project's git repositories
  git:
    repo: '{{ project.git_account }}/{{ item.name }}.git'
    dest: '{{ project.directory }}/{{ item.name }}'
    accept_hostkey: yes
    update: no
  with_items: '{{ project.source_repos }}'

# # TODO: Fix for Her but problem with 'master'
#        # version={{ item.version|default() }}
#   with_items: '{{ proj.group.projects }}'
#   # ignore_errors: yes
