---
- name: Parse developer credentials, write and encrypt them
  include_role:
    name: prepd/credentials
  vars:
    credentials_src_dirs: ['{{ credentials_src_dir }}']
    credentials_action: parse
