---
- name: Set prepd environment variables
  include_role:
    name: prepd/project

#
# - include_role:
#     name: prepd/utils
#     tasks_from: debug

- name: Execute the requested task
  include_tasks: '{{ project_setup_task }}.yml'
