---
- name: Create ROLE and grant dbcreate and superuser privileges
  postgresql_user:
    name: '{{ item.name | default(ansible_user) }}'
    password: '{{ item.password | default(ansible_user) }}'
    role_attr_flags: 'SUPERUSER,CREATEDB'
  with_items: '{{ properties.users }}'
  become: yes
  become_user: postgres

- name: Create a new database
  postgresql_db:
    name: '{{ item.name }}'
    owner: '{{ item.owner }}'
    state: present
  with_items: '{{ properties.databases }}'
  become: yes
  become_user: postgres
