---
- name: Install Debian packages
  apt:
    name: '{{ package }}'
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items: [libpq-dev, postgresql, postgresql-client, postgresql-contrib, python-psycopg2]
  loop_control:
    loop_var: package
  when: ansible_distribution == 'Debian'

- name: Copy .inputrc to postgres home
  copy:
    src: inputrc
    dest: '{{ spec.home }}/.inputrc'
    owner: postgres
  when: ansible_distribution == 'Debian'
