---
- name: Checkout git repositories
  git:
    repo: '{{ item.account }}/{{ item.name }}.git'
    dest: '{{ prepd_tools_dir }}/{{ item.name }}'
    accept_hostkey: yes
    update: no
    version: "{{ item.version | default('HEAD') }}"
  with_items:
    - { name: 'rails-templates', account: 'git@github.com:rjayroach' }
    - { name: 'docker-rails', account: 'git@github.com:rjayroach' }
    - { name: 'lego', account: 'git@github.com:rjayroach' }
    - { name: 'packer', account: 'git@github.com:rjayroach' }
