---
- name: Create directory for tools
  file:
    path: '{{ ansible_env.HOME }}/prepd-tools'
    state: directory
    mode: 0755

- name: "Checkout git repositories"
  git:
    repo: '{{ item.account }}/{{ item.name }}.git'
    dest: '{{ ansible_env.HOME }}/prepd-tools/{{ item.name }}'
    accept_hostkey: yes
    update: no
    version: "{{ item.version | default('HEAD') }}"
  with_items:
    - { name: 'rails-templates', account: 'git@github.com:rjayroach' }
    - { name: 'docker-rails', account: 'git@github.com:rjayroach' }
    - { name: 'lego', account: 'git@github.com:rjayroach' }
