---
- name: Template the inventory roles
  template:
    src: roles.j2
    dest: '{{ playbook_dir }}/inventory/roles'

- name: Setup each environment
  include_tasks: environment.yml
  vars:
    env: '{{ item.key }}'
    env_underscore: "{{ item.key | replace('-', '_') }}"
  with_dict: "{{ setup_inventory_environments }}"
