### Setup credentials and data directories
#
---
- name: Check for existence of ~/prepd
  stat:
    path: '{{ prepd_dir }}'
  register: prepd

# See: https://github.com/ansible/ansible/pull/23104/files
- name: Apply patches to Ansible 2.3
  shell: 'patch < {{ role_path }}/files/{{ item.file }}'
  args:
    chdir: '/usr/local/lib/python2.7/dist-packages/ansible/{{ item.dir }}'
  with_items:
    - { dir: 'playbook', file: 'role_include.py.patch' }
    - { dir: 'executor', file: 'task_executor.py.patch' }
  become: yes
  ignore_errors: yes
  when: prepd.stat.isdir

# NOTE: Files that may be updated by upstream are in the prepd repo
# Files that are not updated by upstream are in prepd-roles repos in this role
- name: Copy user files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    force: no
  with_items:
    - { src: 'ansible/', dest: '{{ ansible_dir }}' }
    - { src: 'terraform/', dest: '{{ terraform_dir }}' }
    - { src: 'kubernetes/', dest: '{{ kubernetes_dir }}' }

- name: provision.yml is executable
  file:
    path: '{{ ansible_dir }}/provisioner.yml'
    mode: 0755

- name: Ensure data and crendentials directories exist in ~/prepd
  file:
    path: '{{ prepd_dir }}/projects/{{ project_name }}/{{ item }}'
    state: directory
  with_items: [credentials, data, vault]
  when: prepd.stat.isdir

- name: Create links to data and credentials directories in ~/prepd
  file:
    src: '{{ prepd_dir }}/projects/{{ project_name }}/{{ item }}'
    dest: '{{ project_dir }}/{{ item }}'
    state: link
  with_items: [credentials, data, vault]
  when: prepd.stat.isdir

- name: Ensure data and crendentials directories exist
  file:
    path: '{{ project_dir }}/{{ item }}'
    state: directory
  with_items: [credentials, data, vault]
  when: not prepd.stat.isdir

- name: Ensure ssh dir exists
  file:
    path: '{{ ssh_dir }}'
    state: directory

- name: Create developer.yml if it does not exist
  template:
    force: no
    src: developer.yml.j2
    dest: '{{ credentials_file }}'

- name: Create vault password file if it does not exist
  template:
    force: no
    src: vault-password.txt.j2
    dest: '{{ vault_dir }}/password.txt'
