### Setup inventory directories
---
- name: Ensure each inventory directory exists
  file:
    path: '{{ playbook_dir }}/inventory/{{ item }}'
    state: directory
  with_items: "{{ ['local'] + setup.environments }}"

- name: Ensure each group_vars directory exists
  file:
    path: '{{ playbook_dir }}/group_vars/{{ item }}'
    state: directory
  with_items: "{{ ['local'] + setup.environments }}"

- template:
    src: inventory-roles.j2
    dest: '{{ playbook_dir }}/inventory/roles'

- name: Softlink the roles file into each inventory directory
  file:
    src: '../roles'
    dest: '{{ playbook_dir }}/inventory/{{ item }}/roles'
    state: link
  with_items: "{{ ['local'] + setup.environments }}"

- name: Softlink the ec2.py file into each inventory directory
  file:
    src: '../ec2.py'
    dest: '{{ playbook_dir }}/inventory/{{ item }}/ec2.py'
    state: link
  with_items: '{{ setup.environments }}'

- name: Template an ec2.ini for each role
  template:
    src: ec2.ini.j2
    dest: '{{ playbook_dir }}/inventory/{{ item }}/ec2.ini'
  with_items: '{{ setup.environments }}'

- name: One time template each inventory hosts file
  template:
    src: inventory-hosts.j2
    dest: '{{ playbook_dir }}/inventory/{{ item }}/hosts'
    force: no
  with_items: '{{ setup.environments }}'
