# Setup a new machine
---
# See: https://github.com/ansible/ansible/pull/23104/files
- name: Apply patches to Ansible 2.4
  shell: 'patch < {{ role_path }}/files/{{ item.file }}'
  args:
    chdir: '/usr/local/lib/python2.7/dist-packages/ansible/{{ item.dir }}'
  with_items:
    - { dir: 'playbook', file: 'role_include.py.patch' }
    - { dir: 'executor', file: 'task_executor.py.patch' }
  become: yes
  # ignore_errors: yes
  # when: prepd.stat.isdir
