### Setup credentials and data directories
---
- name: Check for existence of ~/prepd
  stat:
    path: '{{ prepd_dir }}'
  register: prepd

- name: Ensure data and crendentials directories exist in ~/prepd
  file:
    path: '{{ prepd_dir }}/projects/{{ project_name }}/{{ item }}'
    state: directory
  with_items: [credentials, data]
  when: prepd.stat.isdir

- name: Create links to data and credentials directories in ~/prepd
  file:
    src: '{{ prepd_dir }}/projects/{{ project_name }}/{{ item }}'
    dest: '{{ project_dir }}/{{ item }}'
    state: link
  with_items: [credentials, data]
  when: prepd.stat.isdir

- name: Ensure data and crendentials directories exist
  file:
    path: '{{ project_dir }}/{{ item }}'
    state: directory
  with_items: [credentials, data]
  when: not prepd.stat.isdir

- name: Ensure ssh dir exists
  file:
    path: '{{ ssh_dir }}'
    state: directory

- name: Create developer.yml if it does not exist
  template:
    force: no
    src: developer.yml.j2
    dest: '{{ credentials_file }}'

- name: Create vault password file if it does not exist
  template:
    force: no
    src: vault-password.txt.j2
    dest: '{{ credentials_dir }}/vault-password.txt'

- include: inventory.yml
