### Setup project directories and vault password
---
- name: Ensure data and crendentials directories exist
  file:
    path: '{{ project_data_dir }}/{{ item }}'
    state: directory
  with_items: [credentials, data, vault]

- name: Ensure ssh keys directory exists
  file:
    path: '{{ ssh_dir }}'
    state: directory

- name: Create vault password file if it does not exist
  copy:
    force: no
    content: '{{ 1000000000000 | random | to_uuid }}'
    dest: '{{ vault_dir }}/password.txt'

- name: require vault password in ansible config
  lineinfile:
    path: ansible.cfg
    line: 'vault_password_file = {{ vault_dir }}/password.txt'
    insertafter: 'retry_files_enabled = no'
#
# NOTE: move to prepd-developer
# - name: Create developer.yml if it does not exist
#   template:
#     force: no
#     src: developer.yml.j2
#     dest: '{{ credentials_file }}'
