---
- name: Install common packages
  homebrew: name={{ item }} state=present
  with_items: '{{ common.common_packages }}'

#- homebrew_tap: tap={{ item }} state=present
#  with_items: homebrew_taps

- name: Install homebrew cask
  homebrew: name={{ item }} state=present
  with_items: '{{ common.homebrew_installed_packages }}'

- name: Install packages via cask
  homebrew_cask: name={{ item }} state=present
  with_items: '{{ common.homebrew_cask_apps }}'

- name: Set shell mode to vi and copy in custom tmux.conf
  copy: 'src={{ item }} dest={{ ansible_env.HOME }}/.{{ item }} owner={{ ansible_env.USER }} group=staff mode=0644'
  with_items:
    - inputrc
    - tmux.conf
