---
- homebrew: name={{ item }} state=present
  with_items: common_packages

#- homebrew_tap: tap={{ item }} state=present
#  with_items: homebrew_taps

- homebrew: name={{ item }} state=present
  with_items: homebrew_installed_packages

- homebrew_cask: name={{ item }} state=present
  with_items: homebrew_cask_apps
