---
- name: Install common packages
  apt: 'name={{ item }} state=present update_cache=yes cache_valid_time={{ cache_valid_time|default(86400) }}'
  with_items: '{{ common_packages }}'

- name: Set shell mode to vi
  copy:
    src: inputrc
    dest: '{{ ansible_env.HOME }}/.inputrc'

# TODO: Timezone is per host / region so should be set at the site/inventory level
#- name: Set the locale and the time zone
##  hosts: myhosts
#  sudo: True
#  vars:
#    locale: en_US.UTF-8
#    timezone: Asia/Singapore

- debug: var=machine_env.timezone

- name: Set timezone
# template: src=../templates/debian/timezone.j2 dest=/etc/timezone
# TODO: test if this works
  template: src=debian/timezone.j2 dest=/etc/timezone

- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- debug: var=locale.timezone

#- name: set locale
#  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
#  sudo: true
