---
- name: Check if hugo is installed
  command: dpkg-query -W hugo
  register: package_check_deb
  failed_when: package_check_deb.rc > 1
  changed_when: package_check_deb.rc == 1

- name: Get hugo
  get_url: 
    url: '{{ spec.package_url }}'
    dest: '{{ ansible_env.TMP_DIR }}/{{ spec.package_name }}'
  when: package_check_deb is changed # .rc == 1

- name: Install hugo
  apt:
    deb: '{{ ansible_env.TMP_DIR }}/{{ spec.package_name }}'
  become: yes
  when: package_check_deb is changed # .rc == 1
