# These tasks are called from prepd/credentials/tasks/credential.yml
---
- set_fact:
    provider:
      identifier: '{{ key }}'
      aws_access_key_id: "{{ contents.split('\r\n')[1].split(',')[0] }}"
      aws_secret_access_key: "{{ contents.split('\r\n')[1].split(',')[1] }}"

#
# - name: Template the credentials file
#   blockinfile:
#     create: yes
#     dest: '{{ aws_credentials.dest_dir }}/{{ aws_credentials.dest_file }}'
#     marker: '# {mark} {{ aws_credentials.context }}-{{ aws.identifier }}'
#     block: |
#       [{{ (aws_credentials.context + '-' + aws.identifier) | replace('_', '-') }}]
#       aws_access_key_id = {{ aws.aws_access_key_id }}
#       aws_secret_access_key = {{ aws.aws_secret_access_key }}
