---
- set_fact:
    provider:
      identifier: '{{ key }}'
      aws_access_key_id: "{{ contents.split('\r\n')[1].split(',')[0] }}"
      aws_secret_access_key: "{{ contents.split('\r\n')[1].split(',')[1] }}"
