---
# remove 'default' from the list
aws_inventory_environments: "{{ setup.ec2_ini.keys() | difference(['default']) }}"
        ec2_ini:
          default:
            regions: [ap-southeast-1]
            vpc_destination_variable: ip_address #  private_ip_address
            destination_variable: public_dns_name #  private_dns_name
            boto_profile: default
          development: {}
          staging: {}
          production: {}
