---
- name: Create .tmuxinator directory in home
  file:
    path: '{{ ansible_env.HOME }}/.tmuxinator'
    state: directory
    mode: 0755

- name: Copy tmuxinator files
  copy:
    src: tmuxinator/
    dest: '{{ ansible_env.HOME }}/.tmuxinator/'
