# Sets up ansible project to use aws inventories
# It does NOT setup terraform or any other provisioning tool
---
- include_role:
    name: prepd/project

- include_role:
    name: prepd/utils
    tasks_from: debug

# NOTE: moved to aws/inventory/tasks/main.yml

# TODO: This is maybe not the file or there are more than one files
- include_vars:
    file: '{{ prepd_project_dir }}/vault/credentials/global.yml'

- include_role:
    name: prepd/aws/cli
    tasks_from: credentials
  vars:
    aws_cli_context: '{{ project_name }}'
    aws_cli_credentials: '{{ credentials_aws }}'

# TODO: Tset this; what it should do is put an ec2.py in the inventory and softlink it to each of the ec2_ini.keys()
- include_role:
    name: prepd/aws/inventory
  vars:
    # setup_environments: "{{ setup.ec2_ini.keys() | difference(['default']) }}"
