---
- name: Get project files
  find:
    path: '{{ spec.project_root }}'
    patterns: '*.yml'
  register: project_files
  delegate_to: 127.0.0.1

- include_tasks: project.yml
  with_items: "{{ project_files.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: project_manifest
