---
- name: Install Cordova
  command: npm install -g cordova

- name: Install packages via cask
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
    - android-studio
    # - android-sdk
    # - java
  when: ansible_os_family == 'Darwin'


  # All this is for installing the SDK on a Debian based VM
  # - name: Check if Android SDK is already installed
  #   stat: path=~/src/
  #   register: sdk_dir

  # - name: download Android SDK
  #   # TODO: The dest value is not correct
  #   # TODO: put the version of android SDK in a vars file (or default)
  #   get_url:
  #     url: http://dl.google.com/android/android-sdk_r24.2-linux.tgz
  #     dest: /tmp/yadr_install.sh mode=0755
  #   when: yadr_dir.stat.exists == false
  # 
  #   # TODO: put the JDK in a Java role and depend on that role also
  # - apt: default-jdk, update=true
  # 
  # - name: Accept the SDK and reject the Google Glass linense
  #   shell: echo "y\nn" | tools/android update sdk --no-ui
  #     
  # 
  # # See: https://wiki.debian.org/Multiarch/HOWTO
  # - name: Install i386 arch
  #   command:  dpkg --add-architecture i386
  # 
  # - name: Install i386 packages
  #   apt: libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386

# http://stackoverflow.com/questions/4615145/android-device-is-not-listed-while-running-adb-devices-ubantu-10-10
# http://tools.android.com/recent/updatingsdkfromcommand-line

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: cordova
    aliases_block: |
      alias cv='cordova'
      alias cvb='cordova build'
      alias cvp='cordova plugin'
