---
- name: Install Debian specific packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: '{{ cache_valid_time | default(86400) }}'
  with_items: '{{ developer_common_packages + developer_debian_packages }}'
  when: ansible_distribution == 'Debian'
  become: yes

- name: Install common packages on MacOSX
  homebrew:
    name: '{{ item }}'
    state: present
  with_items: '{{ developer_common_packages + developer_darwin_packages }}'
  when: ansible_distribution == 'MacOSX'

- name: Insert aliases
  blockinfile:
    create: yes
    dest: '{{ machine.aliases_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (developer-tools)'
    block: |
      # Shortcuts for TMux
      alias tl='tmux list-sessions'
      alias ta='tmux a -dt $1'
  when: machine.shell == 'xsh'
