---
- name: Set prepd machine vars
  include_role:
    name: prepd/machine

- name: Set the prepd variables
  set_fact:
    prepd_run_context: developer
    # prepd_dir value comes from this role's vars/main.yml
    # It is set as a fact so that roles that include this role will see the var
    prepd_dir: '{{ prepd_dir }}'
    prepd_developer_dir: '{{ prepd_dir }}/developer'

- name: Include developer variables
  include_vars:
    file: '{{ prepd_developer_dir }}/prepd.yml'
    name: prepd_developer
  when: false
