---
kubernetes_version: 1.5.2

include_services: false
# node1.local is 172.28.128.5
kubernetes_service_ip: 172.28.128.5
kubernetes_master_host: 172.28.128.5
kubernetes_bin_path: /usr/local/bin
kubernetes_var_path: /var/lib/kubernetes
kubernetes_cert_path: '{{ ansible_env.HOME }}/prepd/data/kubernetes'
kubernetes_service_path: /etc/systemd/system

kubernetes_unit_path: '{{ playbook_dir }}/../kubernetes'

# This is set by the calling playbook
mode: 'noop'

bin_type: "{{ 'darwin' if ansible_os_family == 'Darwin' else 'linux' }}"

kubernetes_download_path: 'https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/{{ bin_type }}/amd64'
