---
- name: Install ember
  npm:
    name: ember-cli
    global: yes
  become: yes
  # when: apps|length == 0

- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (ember)'
    block: |
      alias ead='ember deploy:activate development --rev '
      alias eal='ember deploy:activate local --rev '
      alias eap='ember deploy:activate production --rev '
      alias eas='ember deploy:activate staging --rev '

      alias edd='ember deploy development'
      alias edp='ember deploy local'
      alias edp='ember deploy production'
      alias edp='ember deploy staging'

      alias eld='ember deploy:list development'
      alias ell='ember deploy:list local'
      alias elp='ember deploy:list production'
      alias els='ember deploy:list staging'

      alias edep='ember install ember-cli-dotenv ember-cli-deploy ember-cli-deploy-build ember-cli-deploy-s3 ember-cli-deploy-revision-data ember-cli-deploy-display-revisions ember-cli-deploy-s3-index'

      alias es='ember serve'
  # when: apps|length == 0

# TODO: bower doesn't work from ansible for some reason
- name: Install ember project dependencies
  shell: . /etc/profile && npm install # && bower install
  args:
    chdir: '{{ item.dir }}/{{ item.name }}'
  with_items: '{{ apps }}'
  # when: apps|length > 0
