---
- name: Install ember
  npm:
    name: ember-cli
    global: yes
  become: yes
  when: spec.install

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: ember
    aliases_block: |
      edx() {
        if (( $# == 2 )); then
          echo "ember deploy $1.$2"
          ember deploy $1.$2
        else
          echo "ember deploy $1"
          ember deploy $1
        fi
      }

      edd() { edx development $1 }
      eds() { edx staging $1 }
      edp() { edx production $1 }


      elx() {
        if (( $# == 2 )); then
          echo "ember deploy:list $1.$2"
          ember deploy:list $1.$2
        else
          echo "ember deploy:list $1"
          ember deploy:list $1
        fi
      }

      eld() { elx development $1 }
      els() { elx staging $1 }
      elp() { elx production $1 }


      eax() {
        if (( $# == 3 )); then
          echo "ember deploy:activate $1.$2 --rev $3"
          ember deploy:activate $1.$2 --rev $3
        else
          echo "ember deploy:activate $1 -- rev $2"
          ember deploy:activate $1 --rev $2
        fi
      }

      ead() { eax development $1 $2 }
      eas() { eax staging $1 $2 }
      eap() { eax production $1 $2 }

      alias edep='ember install ember-cli-dotenv ember-cli-deploy ember-cli-deploy-build ember-cli-deploy-s3 ember-cli-deploy-revision-data ember-cli-deploy-display-revisions ember-cli-deploy-s3-index'

      alias es='ember serve'

- name: Install ember project dependencies
  # TODO: bower doesn't work from ansible for some reason
  shell: . /etc/profile && npm install # && bower install
  args:
    chdir: "{{ project.value.path | default(spec.project_dir + '/' + project.key) }}"
  with_dict: '{{ spec.projects }}'
  loop_control:
    loop_var: project
