---
- name: Install ember
  npm:
    name: ember-cli
    global: yes
  become: yes
  # when: apps|length == 0

- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (ember)'
    block: |
      alias es='ember serve'
      alias ebp='ember build environment=production'
  # when: apps|length == 0

# TODO: bower doesn't work from ansible for some reason
- name: Install ember project dependencies
  shell: . /etc/profile && npm install # && bower install
  args:
    chdir: '{{ item.dir }}/{{ item.name }}'
  with_items: '{{ apps }}'
  # when: apps|length > 0
