---
- name: Install ember
  npm:
    name: ember-cli
    global: yes
  become: yes
  # when: apps|length == 0

- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (ember)'
    block: |
      alias es='ember serve'
      alias eds='ember deploy local'
      alias edls='ember deploy:list local'
      alias edas='ember deploy:activate local --rev '
      alias edp='ember deploy production'
      alias edlp='ember deploy:list production'
      alias edap='ember deploy:activate production --rev '
      alias eds='ember deploy staging'
      alias edls='ember deploy:list staging'
      alias edas='ember deploy:activate staging --rev '
  # when: apps|length == 0

# TODO: bower doesn't work from ansible for some reason
- name: Install ember project dependencies
  shell: . /etc/profile && npm install # && bower install
  args:
    chdir: '{{ item.dir }}/{{ item.name }}'
  with_items: '{{ apps }}'
  # when: apps|length > 0
