---
- name: Install ember
  npm:
    name: ember-cli
    global: yes
  become: yes
  when: apps is not defined

- name: Install ember dependencies for an existing application
  shell: . /etc/profile && npm install && bower install
  args:
    chdir: '{{ item.dir }}/{{ item.name }}'
  with_items: apps
  when: apps is defined

- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (ember)'
    block: |
      alias es='ember serve'
      alias ebp='ember build environment=production'
  when: apps is not defined
