---
- name: Install package dependencies for debian 
  apt:
    name: '{{ item }}'
    state: present
  become: yes
  with_items: [libreadline-dev, ruby-dev, rbenv, graphviz, bzip2, libssl-dev, zlib1g-dev, g++, libsqlite3-dev]
  when: ansible_distribution == 'Debian'

- name: Clone ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: '{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build'
    update: no

- name: Clone ruby-default-gems
  git:
    repo: https://github.com/rbenv/rbenv-default-gems.git
    dest: '{{ ansible_env.HOME }}/.rbenv/plugins/rbenv-default-gems'
    update: no

- name: Copy rbenv default-gems
  copy:
    src: default-gems
    dest: '{{ ansible_env.HOME }}/.rbenv/default-gems'

- name: Check if the requested ruby version is already installed
  stat:
    path: '{{ ansible_env.HOME }}/.rbenv/versions/{{ properties.version }}'
  register: ruby_dir

- debug: msg='{{ ansible_env.HOME }}/.rbenv/versions/{{ properties.version }}'
- name: 'Install ruby {{ properties.version }}'
  shell: '. /etc/profile && rbenv install {{ properties.version }}'
  when: ruby_dir.stat.isdir is not defined

- name: Set global rbenv version
  shell: '. /etc/profile && rbenv global {{ properties.version }}'
  when: ruby_dir.stat.isdir is not defined


- name: Ensure the ~/.bundle directory exists
  file:
    path: '{{ ansible_env.HOME }}/.bundle'
    state: directory

- name: Create ~/.bundle/config unless it already exists
  template:
    src: bundle_config.j2
    dest: '{{ ansible_env.HOME }}/.bundle/config'
    force: no

- name: Insert aliases
  blockinfile:
    create: yes
    dest: '{{ machine.aliases_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (ruby)'
    block: |
      alias adc='spring rake app:db:clean'
      alias adcm='spring rake app:db:clean:migrate'
      alias adcms='spring rake app:db:clean:migrate:seed'
      alias adcs='spring rake app:db:clean:seed'
      alias adm='spring rake app:db:migrate'
      alias ads='spring rake app:db:seed'
      alias adtp='spring rake app:db:test:prepare'

      alias beg='bundle exec guard'

      alias cop='rubocop'
      alias copa='rubocop -a'
      alias copd='rubocop -D'

      alias dc='spring rake db:clean'
      alias dcm='spring rake db:clean:migrate'
      alias dcms='spring rake db:clean:migrate:seed'
      alias dcs='spring rake db:clean:seed'
      alias dm='spring rake db:migrate'
      alias dms='spring rake db:migrate:status'
      alias ds='spring rake db:seed'
      alias dtp='spring rake db:test:prepare'

      alias fs='foreman start -e <()'

      alias pss='ps -ef|grep spring'

      alias rc='spring rails console'

      alias rg='spring rails generate'
      alias rgjc='spring rails generate jsonapi:controller'
      alias rgjr='spring rails generate jsonapi:resource'
      alias rgm='spring rails generate model'

      # NOTE: bes() only works if there is one line in the Procfile
      function bes() {
        E=`awk '{first = $1; $1 = ""; print $0; }' Procfile`
        eval $E
      }

      function psrk() {
        ps aux | grep ruby | awk '{ print $2 }' | xargs kill -9
      }

      function rgj() {
        spring rails generate jsonapi:controller "$1"
        spring rails generate jsonapi:resource "$1"
      }

      function srs() {
        z $1
        cd spec/dummy
        spring rails server -b 0.0.0.0 -p $2
      }

      alias rk='spring rake'
      alias rkd='RAILS_ENV=test spring rake docs:generate'

      alias rs='spring rspec'

      alias sgpl='spring stop; git checkout Gemfile.lock; git pull'
      alias src='spring stop; rc'
      alias ss='spring stop'
