---
- set_fact:
    role: "{{ ruby|combine(project.ruby|default({})) }}"

- name: Install Debian packages
  apt: name={{ item }} state=present
  become: yes
  with_items: [libreadline-dev, ruby-dev, rbenv]
  when: ansible_distribution == 'Debian'

- name: Clone ruby-build
  git: repo=https://github.com/rbenv/ruby-build.git dest={{ ansible_env.HOME }}/.rbenv/plugins/ruby-build update=no

- name: Clone ruby-default-gems
  git: repo=https://github.com/rbenv/rbenv-default-gems.git dest={{ ansible_env.HOME }}/.rbenv/plugins/rbenv-default-gems update=no

- name: Copy default-gems for .rbenv
  copy: src=default-gems dest={{ ansible_env.HOME }}/.rbenv/default-gems

- name: Check if ruby version is installed
  stat: path={{ ansible_env.HOME }}/.rbenv/versions/{{ role.version }}
  register: ruby_dir

- name: 'Install ruby {{ role.version }}'
  shell: . /etc/profile && rbenv install {{ role.version }}
  when: ruby_dir.stat.isdir is not defined

- name: Set global rbenv version
  shell: . /etc/profile && rbenv global {{ role.version }}
  when: ruby_dir.stat.isdir is not defined
