---
- set_fact:
    role: "{{ mysql|combine(project.mysql|default({})) }}"

- name: Install Debian packages
  apt: name={{ item }} state=present
  become: yes
  with_items: [libmysqlclient-dev, mysql-client, mysql-server, python-mysqldb]
  when: ansible_distribution == 'Debian'

# TODO: Test this one
# NOTE: The location of the my.cnf can be operating system dependent, e.g. ubuntu is diff from debian
# - name: update MySQL configuration to use per table inno db
#   lineinfile: dest=/etc/mysql/my.cnf regexp='mysqld\]' insertafter='innodb_buffer_pool_size=4G'
# 
# - lineinfile: dest=/etc/mysql/my.conf regexp='mysqld\]' insertafter='innodb_log_file_size=1G'
# - lineinfile: dest=/etc/mysql/my.conf regexp='mysqld\]' insertafter='innodb_flush_method=O_DIRECT'
# - lineinfile: dest=/etc/mysql/my.conf regexp='mysqld\]' insertafter='innodb_file_per_table'
