---
- name: Install dependencies
  apt:
    name: nfs-kernel-server
    state: present
  become: yes

- name: Check if Vagrant is installed
  shell: which vagrant
  register: result
  failed_when: false
  changed_when: false

- name: Get Vagrant .deb
  get_url:
    url: 'https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb'
    dest: '{{ ansible_env.TMPDIR }}/vagrant_{{ vagrant_version }}_x86_64.deb'
    checksum: '{{ vagrant_checksum }}'
  register: new_archive
  become: yes
  when: result.rc == 1 # binary is not installed

- name: Install Vagrant .deb
  apt:
    deb: '{{ ansible_env.TMPDIR }}/vagrant_{{ vagrant_version }}_x86_64.deb'
  become: yes
  when: new_archive is changed
