---
- name: Install Vagrant and related packages
  homebrew_cask: 'name={{ item }} state=present'
  with_items:
    - vagrant
    - vagrant-manager
    - virtualbox
  when: ansible_os_family == 'Darwin'

# TODO: Add the vagrant plugins installations as well
 
- name: Check if zsh aliases file exists
  stat:
    path: ~/.zsh.after/aliases.zsh
  register: zsh_aliases

- name: Insert aliases
  blockinfile:
    dest: ~/.zsh.after/aliases.zsh
    block: |
      alias v='vagrant'
      alias vb='vagrant box'
      alias vd='vagrant destroy'
      alias vdm='vagrant destroy --force master'
      alias vg='vagrant global-status'
      alias vh='vagrant halt'
      alias vhm='vagrant halt master'
      alias vp='vagrant provision'
      alias vpm='vagrant provision master'
      alias vs='vagrant ssh'
      alias vsm='vagrant ssh master'
      alias vst='vagrant status'
      alias vu='vagrant up'
      alias vum='vagrant up master'
      alias vup='vagrant up --provision'
      alias vhn="bash -lc 'vagrant halt /swarm-node[0-9]/'"
      alias vun="bash -lc 'vagrant up /swarm-node[0-9]/'"
  when: zsh_aliases.stat.exists
