---
- name: Install Vagrant and related packages
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items: [vagrant, vagrant-manager]
  when: ansible_os_family == 'Darwin'

- name: Get Vagrant .deb
  get_url:
    url: 'https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.deb'
    dest: '{{ ansible_env.TMPDIR }}/vagrant_2.0.3_x86_64.deb'
    checksum: sha256:47ea8af7644616caf36d421ecf2e0aceb1f5095933a2bfc2d50b7b8bae35d93f
  # when: not binary_file.stat.exists
  register: new_archive
  when: ansible_os_family == 'Debian'

- name: Install Vagrant .deb
  apt:
    deb: '{{ ansible_env.TMPDIR }}/vagrant_2.0.3_x86_64.deb'
  become: yes
  when: ansible_os_family == 'Debian'

# TODO: tasks to install vagrant on Linux/Ubuntu

- name: Install Vagrant plugins
  include_tasks: plugin.yml
  with_items:
    - vagrant-vbguest      # keep your VirtualBox Guest Additions up to date
    - vagrant-cachier      # caches guest packages
    - vagrant-hostmanager  # updates /etc/hosts file when machines go up/down
  loop_control:
    loop_var: plugin

- stat:
    path: /opt/vagrant/embedded/bin/curl
  register: curl

# NOTE: http://stackoverflow.com/questions/23874260/error-when-trying-vagrant-up
- name: "Remove Vagrant's built in curl which fails to download boxes on Mac"
  file:
    path: /opt/vagrant/embedded/bin/curl
    state: absent
  become: yes
  when: curl.stat.exists and ansible_os_family == 'Darwin'

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: vagrant
    aliases_block: |
      alias v='vagrant'
      alias vb='vagrant box'
      alias vd='vagrant destroy'
      vh() { vagrant halt "${1:=node0}" }
      # Halt all vagrant machines
      alias vha='vagrant halt'
      vp() { vagrant provision "${1:=node0}" }
      vsh() { vagrant ssh "${1:=node0}" }
      alias vst='vagrant status'
      alias vstg='vagrant global-status'
      vu() { vagrant up "${1:=node0}" }

- name: Ensure User's .ssh directory exists
  file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory
    mode: 0755

- name: Set IP address type and allow ssh agent forwarding to local virtual machines in ~/.ssh/config
  blockinfile:
    create: yes
    dest: ~/.ssh/config
    marker: '# {mark} ANSIBLE MANAGED BLOCK (vagrant)'
    block: |
      Host *.local
        User vagrant
        ForwardAgent yes
        AddressFamily inet
