---
# NOTE: This item will fail the first time
# User first needs to open Security Settings and allow kernel externsions from Oracle America.
# Then re-run this playbook
- name: Install Virtualbox
  homebrew_cask:
    name: virtualbox
    state: present
  when: ansible_os_family == 'Darwin'

- name: Install Vagrant and related packages
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items: [vagrant, vagrant-manager]
  when: ansible_os_family == 'Darwin'

# TODO: tasks to install vagrant on Linux/Ubuntu

- name: Install Vagrant plugins
  include_tasks: plugin.yml
  with_items:
    - vagrant-vbguest      # keep your VirtualBox Guest Additions up to date
    - vagrant-cachier      # caches guest packages
    - vagrant-hostmanager  # updates /etc/hosts file when machines go up/down
  loop_control:
    loop_var: plugin
 
# NOTE: http://stackoverflow.com/questions/23874260/error-when-trying-vagrant-up
- name: "Remove Vagrant's built in curl which fails to download boxes on Mac"
  file:
    path: /opt/vagrant/embedded/bin/curl
    state: absent
  become: yes
  when: ansible_os_family == 'Darwin'

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: vagrant
    aliases_block: |
      alias v='vagrant'
      alias vb='vagrant box'
      alias vd='vagrant destroy'
      vh() { vagrant halt "${1:=node0}" }
      # Halt all vagrant machines
      alias vha='vagrant halt'
      vp() { vagrant provision "${1:=node0}" }
      vsh() { vagrant ssh "${1:=node0}" }
      vst() { vagrant status "${1:=node0}" }
      alias vstg='vagrant global-status'
      vu() { vagrant up "${1:=node0}" }
