---
- name: Install Vagrant and related packages
  homebrew_cask: 'name={{ item }} state=present'
  with_items:
    - vagrant
    - vagrant-manager
    - virtualbox
  when: ansible_os_family == 'Darwin'

# TODO: Add the vagrant plugins installations as well
 
- name: Check if zsh aliases file exists
  stat:
    path: ~/.zsh.after/aliases.zsh
  register: zsh_aliases

- name: Insert aliases
  blockinfile:
    dest: ~/.zsh.after/aliases.zsh
    block: |
      alias v='vagrant'
      alias vb='vagrant box'
      alias vd='vagrant destroy'
      alias vd0='vagrant destroy --force node0'
      alias vg='vagrant global-status'
      alias vh='vagrant halt'
      alias vh0='vagrant halt node0'
      alias vp='vagrant provision'
      alias vp0='vagrant provision node0'
      alias vs='vagrant ssh'
      alias vs0='vagrant ssh node0'
      alias vst='vagrant status'
      alias vu='vagrant up'
      alias vu0='vagrant up node0'
      alias vup='vagrant up --provision'
      alias vhn="bash -lc 'vagrant halt /node[1-9]/'"
      alias vun="bash -lc 'vagrant up /node[1-9]/'"
  when: zsh_aliases.stat.exists
