---
- name: 'Install Vagrant on detected OS ({{ ansible_os_family }})'
  include_tasks: '{{ ansible_os_family | lower }}.yml'

- name: Install Vagrant plugins
  include_tasks: plugin.yml
  with_items: '{{ vagrant_plugins }}'
  loop_control:
    loop_var: plugin

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: vagrant
    aliases_block: |
      alias v='vagrant'
      alias vb='vagrant box'
      alias vd='vagrant destroy'
      vh() { vagrant halt "${1:=node0}" }
      # Halt all vagrant machines
      alias vha='vagrant halt'
      vp() { vagrant provision "${1:=node0}" }
      vsh() { vagrant ssh "${1:=node0}" }
      alias vst='vagrant status'
      alias vstg='vagrant global-status'
      vu() { vagrant up "${1:=node0}" }

- name: Ensure User's .ssh directory exists
  file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory
    mode: 0755

- name: Set IP address type and allow ssh agent forwarding to local virtual machines in ~/.ssh/config
  blockinfile:
    create: yes
    dest: ~/.ssh/config
    marker: '# {mark} ANSIBLE MANAGED BLOCK (vagrant)'
    block: |
      Host *.local
        User vagrant
        ForwardAgent yes
        AddressFamily inet
