---
- include_vars:
    dir: '{{ provider_dir.path }}'
    name: provider_credentials
    files_matching: .yml

- set_fact:
    _append_dict: "{ '{{ provider_name }}': {{ provider_credentials }} }"

- set_fact:
    prepd_credentials: '{{ prepd_credentials | combine(_append_dict) }}'
