---
- name: Debug credentials
  debug:
    var: credentials
    verbosity: 0

# Process all projects by passing in an list of project names
# If processing a single project, convert it to a list first
- include_tasks: project.yml
  with_items: '{{ credentials.project_names }}'
  loop_control:
    loop_var: credentials_project_name
