---
- name: Get a list of all raw credential files in the project's vault
  find:
    paths: '{{ credentials.src_dir }}/{{ credentials_project_name }}/vault/credentials/{{ credentials.provider }}'
    patterns: '*.{{ credentials.src_pattern }}'
  register: src_files

- name: Convert all source files to YAML
  include_tasks: source-credentials-to-yaml.yml key="{{ item.path.split('/')[-1].split('.')[0] }}" file_path='{{ item.path }}'
  with_items: '{{ src_files.files }}'

#
#- name: Get a list of YAML files in the project's vault
#  find:
#    paths: '{{ credentials.src_dir }}/{{ credentials_project_name }}/vault/credentials/{{ credentials.provider }}'
#    patterns: '*.yml'
#  register: credentials_yaml_files
#  when: false
#
#- debug:
#    var: credentials_yaml_files
#    verbosity: 1
#  when: false
