---
- debug:
    var: '{{ debug_item }}'
    verbosity: 0
  with_items: [key, file_path, credentials]
  loop_control:
    loop_var: debug_item

# NOTE: dynamic name and tasks_from for include_role are not currently supported so each provider's callback needs to be hardcoded
# TODO: if/when dynamic is supported then each caller should provide a role name and tasks_from when invoking the credentials role
- name: Convert the contents of a single source file to YAML
  include_role:
    name: prepd/aws/credentials
    tasks_from: source-credentials-to-yaml
  vars:
    dest: '{{ credentials.src_dir }}/{{ credentials_project_name }}/vault/credentials/{{ credentials.provider }}/{{ key }}.yml'
    contents: "{{ lookup('file', file_path) }}"
    context: '{{ credentials_project_name }}'
  when: credentials.provider == 'aws'

- name: Encrypt the yaml file
  command: "ansible-vault encrypt {{ file_path | regex_replace(credentials.src_pattern + '$', 'yml') }}"

- name: Delete the source file
  file:
    path: '{{ item.path }}'
    state: absent
  when: false
