---
- name: Get a list of all credential providers for this source
  find:
    paths: '{{ source_dir }}'
    file_type: directory
  register: credential_providers

- name: "Invoke the action '{{ credentials.action }}' on each provider"
  include_tasks: '{{ credentials.action }}.yml'
  vars:
    provider_name: "{{ provider_dir.path.split('/')[-1] }}"
  with_items: '{{ credential_providers.files }}'
  loop_control:
    loop_var: provider_dir
