---
- name: Get the current status of minikube
  command: minikube status
  register: mks
  changed_when: false
  failed_when: false

- set_fact:
    minikube_running: "{{ mks.stdout_lines[0].split(' ')[-1] == 'Running' }}"

- name: Start minikube
  include_tasks: start.yml
  when: not minikube_running
