---
# if project-root/.boto exists then link it to ~/.boto and download ec2.py and ec2.ini and chmod ec2.py
- stat:
    path: '{{ credentials_dir }}/boto'
  register: boto

- name: Link credentials_dir/boto to ~/.boto if the file exists
  file:
    src: '{{ boto.stat.path }}'
    dest: '{{ ansible_env.HOME }}/.boto'
    state: link
  when: boto.stat.exists == true

- name: Install boto
  pip:
    name: boto
    state: present
  when: boto.stat.exists == true

- stat:
    path: '{{ credentials_dir }}/id_rsa'
  register: id_rsa

- name: Link credentials_dir/id_rsa and id_rsa.pub to ~/.ssh if the files exist
  file:
    src: '{{ credentials_dir }}/{{ item }}'
    dest: '{{ ansible_env.HOME }}/.ssh/{{ item }}'
    state: link
  when: id_rsa.stat.exists == true
  with_items:
    - id_rsa
    - id_rsa.pub
