---
- name: Ensure the terraform credentials directory exists
  file:
    path: '{{ credentials_dir }}/terraform'
    state: directory

- include_vars:
    file: '{{ credentials_dir }}/aws/terraform.yml'
    name: aws_keys

- name: Generate tfvars for each terraform credential
  template:
    src: terraform-credentials.tfvars.j2
    dest: "{{ credentials_dir }}/terraform/{{ item.key.split('_')[-1] }}.tfvars"
  with_dict: '{{ aws_keys }}'

- name: Generate terraform.tfvars
  template:
    src: terraform.tfvars.j2
    dest: '{{ tf_dir }}/terraform.tfvars'
    force: no

- name: Ensure the terragrunt temp directory is clean
  file:
    path: '{{ terragrunt_dir }}'
    state: absent

- name: Ensure the component directory tree exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ tf_components_dir }}'
    - '{{ tf_dir }}/{{ service }}'
