---
- include_role:
    name: prepd/project

- include_role:
    name: prepd/utils
    tasks_from: debug

- name: Execute the requested task
  include_role:
    name: terraplate/setup
  when: terraplate.task == 'setup'

- name: Execute the requested task
  include_role:
    name: terraplate/domain
  when: terraplate.task == 'app' or terraplate.task == 'lib'
