---
- set_fact:
    source_directory: '{{ proj.group.source_directory }}'
    image_directory: '{{ proj.group.image_directory }}'
    image_directory_suffix: '{{ proj.group.image_directory_suffix }}'

- name: Add project to bundle/config
  lineinfile:
    dest: ~/.bundle/config
    state: present
    line: 'BUNDLE_LOCAL__{{ item.local }}: "{{ source_directory }}/{{ item.name }}"'
  with_items: '{{ proj.group.projects }}'
  when: item.local is defined

- name: Run bundle on build projects
  shell: . /etc/profile && ~/.rbenv/shims/bundle
  args:
    chdir: '{{ source_directory }}/{{ item.name }}'
  with_items: '{{ proj.group.projects }}'
  when: item.build is defined

# - debug: "msg='{{ image_directory }}/{{ item.name }}{{ image_directory_suffix }}'"
#   with_items: '{{ proj.group.projects }}'

- name: Run database migrations on engine build projects
  shell: . /etc/profile && ~/.rbenv/shims/bundle exec rake {{ 'app:' if item.engine is defined else '' }}db:migrate {{ 'app:' if item.engine is defined else '' }}db:test:prepare
  args:
    chdir: '{{ source_directory }}/{{ item.name }}'
  with_items: '{{ proj.group.projects }}'
  when: item.build is defined
