---
# - set_fact:
#     role: "{{ rails|combine(project.rails|default({})) }}"

# - include: env-config.yml proj={{ outer_item }}
#   with_items: '{{ project_groups }}'
#   loop_control:
#     loop_var: outer_item
# 
# - include: bundle-config.yml

- include: bundle-projects.yml proj={{ outer_item }}
  with_items: '{{ project_groups }}'
  loop_control:
    loop_var: outer_item
