# Options:
# link_env: when yes, a soft link will be made to ../.env
# engine: when yes, the env file will be linked in spec/dummy
# local: when yes, the repo will be added to ~/.bundle/config as a local source
# bundle: when yes, bundle will be run after the repository is downloaded
# migrate: when yes, bundle exec rake (app:)db:migrate and (app:)db:test:prepare will be run after bundle
---
- name: Bundle dependencies
  shell: . /etc/profile && ~/.rbenv/shims/bundle
  args:
    chdir: '{{ chdir }}'
  when: bundle

- name: Run database migrations
  shell: . /etc/profile && ~/.rbenv/shims/bundle exec rake {{ 'app:' if engine else '' }}db:migrate {{ 'app:' if engine else '' }}db:test:prepare
  args:
    chdir: '{{ chdir }}'
  when: bundle and migrate

- name: Create softlinks to the .env file in the project parent directory
  file:
    path: '{{ chdir }}/.env'
    src: "{{ chdir.split('/')[0:-1] | join('/') }}/.env"
    state: link
  when: link_env

- name: Create softlinks to the project .env file in spec/dummy for engines
  file:
    path: '{{ chdir }}/spec/dummy/.env'
    src: '{{ chdir }}/.env'
    state: link
  with_items: '{{ rails_apps }}'
  when: engine

- name: Configure repo as a local source in ~/.bundle/config
  lineinfile:
    dest: ~/.bundle/config
    state: present
    line: 'BUNDLE_LOCAL__{{ item.name.replace("-", "_").upper() }}: "{{ item.dir | default(rails_dir) }}/{{ item.name }}"'
  with_items: '{{ rails_apps }}'
  when: false # local
