---
- name: Run bundle
  shell: . /etc/profile && ~/.rbenv/shims/bundle
  args:
    chdir: '{{ item.dir | default(rails_dir) }}/{{ item.name }}'
  with_items: '{{ rails_apps }}'
  when: item.bundle is defined and item.bundle

- name: Run database migrations
  shell: . /etc/profile && ~/.rbenv/shims/bundle exec rake {{ 'app:' if item.engine is defined else '' }}db:migrate {{ 'app:' if item.engine is defined else '' }}db:test:prepare
  args:
    chdir: '{{ item.dir | default(rails_dir) }}/{{ item.name }}'
  with_items: '{{ rails_apps }}'
  when: item.migrate is defined and item.migrate

- include_tasks: config.yml
