---
- name: Get Helm
  unarchive:
    src: 'https://storage.googleapis.com/kubernetes-helm/helm-{{ spec.version }}-{{ spec.arch }}.tar.gz'
    dest: '{{ spec.bin_dir }}'
    remote_src: yes
    creates: '{{ spec.bin_dir }}/helm'
    exclude: [LICENSE, README.md]
  become: yes

- name: Move binary to path
  command: 'mv {{ spec.arch }}/helm {{ spec.bin_dir }}'
  args:
    chdir: '{{ spec.bin_dir }}'
    creates: '{{ spec.bin_dir }}/helm'
  become: yes

- name: 'Remove {{ spec.arch }}'
  file:
    path: '{{ spec.bin_dir }}/{{ spec.arch }}'
    state: absent
  become: yes

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: k8s-helm
    aliases_block: |
      source <(helm completion zsh) 
