---
- debug:
    var: '{{ debug_item }}'
    verbosity: 0
  with_items: [provider_name, key, file_path, file_path_yml]
  loop_control:
    loop_var: debug_item

- name: Invoke the provider's task
  include_tasks: 'providers/{{ provider_name }}.yml'
  vars:
    contents: "{{ lookup('file', file_path) }}"

- debug:
    var: provider
    verbosity: 0

- name: Convert the contents to YAML
  template:
    src: '{{ provider_name }}.yml.j2'
    dest: '{{ file_path_yml }}'

- name: Encrypt the yaml file
  command: 'ansible-vault encrypt {{ file_path_yml }}'
  when: credentials.encrypt

- name: Delete the source file
  file:
    path: '{{ file_path }}'
    state: absent
  when: credentials.delete_src
