---
- name: "Get a list of all raw credential files for provider '{{ provider_name }}'"
  find:
    paths: '{{ provider_dir.path }}'
    patterns: '*.{{ credentials.providers[provider_name].src_pattern }}'
  register: src_files

- name: Process each raw credential file
  include_tasks: credential.yml
  vars:
    key: "{{ item.path.split('/')[-1].split('.')[0] }}"
    file_path: '{{ item.path }}'
    file_path_yml: "{{ item.path | regex_replace(credentials.providers[provider_name].src_pattern + '$', 'yml') }}"
  with_items: '{{ src_files.files }}'

- debug:
    var: src_files
    verbosity: 1
