---
# - debug: var=tfvars
# - debug: var=tfvars.cidr_blocks
# - debug: msg="{{ 999999999999999999999 | random | to_uuid | hash('md5') }}"

- name: Template the {{ module_meta.name }} component
  template:
    src: common.j2
    dest: '{{ component_dir }}/{{ module_meta.name }}.tf'

- name: Add {{ module_meta.name }} variables to .tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK ({{ module_meta.name }})'
    block: |
      {% for key, value in tfvars.iteritems() %}
      {{ module_meta.name | replace('-', '_') }}_{{ key }}{{ ' ' * (30 - (key | length)) }}= "{{ value }}"
      {% endfor %}
