---
- name: Merge bastion vars
  set_fact:
    attrs: "{{ bastion_defaults | combine(bastion) }}"

- include: get-current-ip.yml attribute=access_cidr
  when: attrs.access_cidr == 'current-ip'

- include_vars: app-server-with-elb.yml
- include: common-tasks.yml
