---
- name: Template the hostname component
  template:
    src: hostname.j2
    dest: '{{ component_dir }}/hostname.tf'

- name: Add hostname module variables to .tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (hostname)'
    block: |
      hostname_name = "{{ hostname.name }}"
