---
- name: Merge key pair vars
  set_fact:
    attrs: "{{ key_pair_defaults | combine(provision.tfvars | default({})) }}"

- include_vars: key-pair.yml

- name: Generate SSH key pair
  shell: 'ssh-keygen -b 2048 -t rsa -f {{ tfvars.public_key_path }} -q -N ""'
  args:
    creates: '{{ tfvars.public_key_path }}'

- name: Update local ssh config
  blockinfile:
    create: yes
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    marker: '# {mark} ANSIBLE MANAGED BLOCK ({{ tfvars.key_name }})'
    block: |
      Host {{ tfvars.key_name }}
        IdentityFile {{ tfvars.public_key_path }}

- include: common-tasks.yml
