# components/<service>/<resource>/<component>/<module>.tf
# components/recheck-lite/pro/api-server/vpc-public-only.tf
# components/recheck-lite/pro/api-server/vpc-public-only.tf

# <service>/<infrastructure_env>/<resource>/<component>/terraform.tfvars
# recheck-lite/staging/processor/api-server/terraform.tfvars
---
# - name: Ensure the environment and component directory is clean
#   file:
#     path: '{{ item }}'
#     state: absent
#   with_items:
#     - '{{ tf_components_dir }}/{{ service }}/{{ component_namespace | default(resource) }}/{{ component }}'
#     - '{{ tf_environments_dir }}/{{ infrastructure_env }}/{{ service }}/{{ resource }}/{{ resource_name | default(component) }}'

- name: Ensure the environment and component directory tree exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ tf_components_dir }}/{{ service }}/{{ component_namespace | default(resource) }}'
    - '{{ tf_components_dir }}/{{ service }}/{{ component_namespace | default(resource) }}/{{ component }}'
    - '{{ tf_dir }}/{{ service }}/{{ infrastructure_env }}/{{ resource }}/{{ resource_name | default(component) }}'

- debug: var=module
- debug: var=component

- name: Set var names
  set_fact:
    component_var_name: "{{ service | replace('-', '_') }}_{{ (component_namespace | default(resource)) | replace('-', '_') }}"
    instance_var_name: "{{ (resource_name | default(component)) | replace('-', '_') }}"
    # TODO: The next two need to be changed so they can inherit from the instance
    remote_state_var_name: "{{ service | replace('-', '_') }}_remote_state"
    provider_var_name: "{{ service | replace('-', '_') }}_provider"
#
- debug: var=component_var_name
- debug: var=instance_var_name

- name: Get component values
  set_fact:
    component_hash: "{{ hostvars[inventory_hostname][component_var_name] | default({}) }}"
    instance_hash: "{{ hostvars[inventory_hostname][(service | replace('-', '_')) + '_' + (resource | replace('-', '_'))] | default({}) }}"
#
- debug: var=component_hash
- debug: var=instance_hash

- name: Get instance values
  set_fact:
    component_vars: "{{ component_hash[component | replace('-', '_')] | default({}) }}"
    instance_vars: '{{ instance_hash[instance_var_name] | default({}) }}'
#
- debug: var=component_vars
- debug: var=instance_vars

- name: Merge component and instance values
  set_fact:
    provision:
      tfvars: '{{ (component_vars.tfvars | default({})) | combine(instance_vars.tfvars | default({})) }}'
      remote_state: '{{ hostvars[inventory_hostname][remote_state_var_name] }}'
      provider: '{{ hostvars[inventory_hostname][provider_var_name] }}'
#
- debug: var=provision

- include: '{{ item }}.yml'
  with_items: "{{ ['provider', 'remote-state', module] }}"
