# components/<service>/<resource>/<component>/<module>.tf
# components/recheck-lite/pro/api-server/vpc-public-only.tf
# components/recheck-lite/pro/api-server/vpc-public-only.tf

# <service>/<infrastructure_env>/<resource>/<component>/terraform.tfvars
# recheck-lite/staging/processor/api-server/terraform.tfvars
---
# - name: Ensure the environment and component directory is clean
#   file:
#     path: '{{ item }}'
#     state: absent
#   with_items:
#     - '{{ tf_components_dir }}/{{ service }}/{{ res_key | default(resource) }}/{{ component }}'
#     - '{{ tf_environments_dir }}/{{ infrastructure_env }}/{{ service }}/{{ resource }}/{{ inf_key | default(component) }}'

- name: Ensure the environment and component directory tree exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ tf_components_dir }}/{{ service }}/{{ res_key | default(resource) }}'
    - '{{ tf_components_dir }}/{{ service }}/{{ res_key | default(resource) }}/{{ component }}'
    - '{{ tf_dir }}/{{ service }}/{{ infrastructure_env }}/{{ resource }}/{{ inf_key | default(component) }}'

#- include: get-current-ip.yml
#  when: provision.web_app_allowed_hosts == 'current-ip' or provision.vpc_bastion_cidr == 'current-ip'

- include: '{{ item }}.yml'
  with_items: "{{ ['provider', 'remote-state'] + modules }}"
