---
- name: Template the Providers
  template:
    src: provider.j2
    dest: '{{ component_dir }}/providers.tf'

- name: Add terragrunt config to tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (terragrunt)'
    block: |
      terragrunt = {
        terraform {
          source = "{{ component_path }}"
          extra_arguments "secrets" {
            arguments = [
              "-var-file={{ credentials_dir }}/terraform/{{ provider }}.tfvars",
            ]
            commands = [
              "apply", "plan", "import", "push", "refresh", "destroy"
            ]
          }
        }
        include = {
          path = "${find_in_parent_folders()}"
        }
      {% if dependencies is defined %}
        dependencies {
          paths = [
      {% for item in dependencies %}
            "../../{{ item }}",
      {% endfor %}
          ]
        }
      {% endif %}
      }
      region = "{{ region }}"
