---
- name: Merge rds vars
  set_fact:
    attrs: '{{ rds_defaults | combine(provision.tfvars | default({})) }}'

- debug: var=attrs
- include_vars: rds.yml

- name: Ensure rds app credentials file exists
  copy:
    dest: '{{ attrs.ansible_vars_file }}'
    force: no
    content: ''

- include: common.yml
