---
- name: Merge rds vars
  set_fact:
    attrs: "{{ rds_defaults | combine(rds) }}"

- name: Ensure rds app credentials file exists
  copy:
    dest: '{{ attrs.ansible_vars_file }}'
    force: no
    content: ''

- name: Template the rds component
  template:
    src: rds.j2
    dest: '{{ component_dir }}/rds.tf'

- name: Add rds variables to .tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (rds)'
    block: |
      db_allocated_storage = "{{ attrs.db_allocated_storage }}"
      db_availability_zone = "{{ attrs.db_availability_zone }}"
      db_engine = "{{ attrs.db_engine }}"
      db_identifier = "{{ attrs.db_identifier }}"
      db_instance_type = "{{ attrs.db_instance_type }}"
      db_name = "{{ attrs.db_name }}"
      db_parameter_group_name = "{{ attrs.db_parameter_group_name }}"
      db_password = "{{ attrs.db_password }}"
      db_storage_encrypted = "{{ attrs.db_storage_encrypted }}"
      db_username = "{{ attrs.db_username }}"
      db_env_file = "{{ attrs.ansible_vars_file }}"
      db_ansible_vars_key = "tf_{{ application_name }}_rds"
      # db_cidr_blocks
