---
- name: Template the Remote State
  template:
    src: remote-state.j2
    dest: '{{ component_dir }}/remote-state.tf'
  when: remote_states is defined

- name: Add vpc module variables to .tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (remote-state)'
    block: |
      tf_remote_state_bucket = "{{ provision.tf_remote_state_bucket }}"
      tf_remote_state_region = "{{ provision.tf_remote_state_region }}"
      tf_remote_state_environment = "{{ infrastructure_env }}"
      tf_resource = "{{ resource }}"
