---
- name: Template the Remote State
  template:
    src: remote-state.j2
    dest: '{{ component_dir }}/remote-state.tf'
  when: remote_states is defined

- name: Add remote-state variables to .tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (remote-state)'
    block: |
      remote_state_bucket = "{{ provision.remote_state.bucket }}"
      remote_state_region = "{{ provision.remote_state.region }}"

      {% for key, value in remote_states.iteritems() %}
      {% if value.startswith('global') %}
      remote_state_key_{{ key }} = "{{ value }}"
      {% elif value.split('/') | length == 1 %}
      remote_state_key_{{ key }} = "{{ service }}/{{ infrastructure_env }}/{{ resource }}/{{ value }}"
      {% else %}
      remote_state_key_{{ key }} = "{{ service }}/{{ infrastructure_env }}/{{ value }}"
      {% endif %}
      {% endfor %}
