---
- name: Ensure app credentials file exists
  copy:
    dest: '{{ ansible_vars_file_s3_website }}'
    force: no
    content: ''

- name: Template the web-app component
  template:
    src: s3-website.j2
    dest: '{{ component_dir }}/s3-website.tf'

- name: Add s3-website variables to .tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (s3-website)'
    block: |
      web_app_allowed_hosts = "{{ provision.web_app_allowed_hosts }}"
      web_app_api_url = "{{ web_app.API_URL }}"
      web_app_application = "{{ application_name }}"
      web_app_app_host = "{{ web_app.APP_HOST }}"
      web_app_credentials_file = "{{ ansible_vars_file_s3_website }}"
      web_app_environment = "{{ infrastructure_env }}"
      web_app_iam_user_name = "{{ infrastructure_env }}-{{ service }}-{{ resource }}-s3"
      web_app_region = "{{ provision.tf_aws_region }}"
