---
- name: Merge s3_website vars
  set_fact:
    attrs: "{{ s3_website_defaults | combine(provision.tfvars) }}"

- include: get-current-ip.yml attribute=access_cidr
  when: attrs.access_cidr == 'current-ip'

- name: Ensure app credentials file exists
  copy:
    dest: '{{ attrs.credentials_file }}'
    force: no
    content: ''

- include_vars: s3-website.yml
- include: common.yml
