# TODO: The underlying tf module, e.g. public-only, public-private-vpn can be a default var in this role
---
- name: Template the VPC component
  template:
    src: vpc-public-private-vpn.j2
    dest: '{{ component_dir }}/vpc-public-private-vpn.tf'

- name: Add vpc module variables to .tfvars
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (vpc-public-private-vpn)'
    block: |
      vpc_tag_name = "{{ service }}-{{ infrastructure_env }}-{{ resource }}-{{ inf_key | default(component) }}"
      vpc_subnet_az_public = "{{ vpc_subnet_az_public }}"
      vpc_subnet_az_private = "{{ vpc_subnet_az_private }}"
