---
- name: Generate an SSH key for Ansible to use with AWS
  shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/ansible_aws_rsa -q -N ""
  args:
    creates: ~/.ssh/ansible_aws_rsa

# Create a new ec2 key pair named ansible if not present using provided key material
- name: Upload Ansible ec2 key to AWS
  ec2_key:
    name: Ansible
    key_material: '{{ item }}'
    # region: ap-southeast-1
    region: us-east-1
  with_file: ~/.ssh/ansible_aws_rsa.pub
