---
- debug: msg='AWS Networking Destroy!!'

- include_vars: '{{ aws.vpc_info_file }}'

- name: '{{ domain }} - Create empty Web Tier Security Group'
  ec2_group:
    region: '{{ region }}'
    vpc_id: '{{ vpd.vpc_id }}'
    name: '{{ domain_tag }}-sg-web'
    description: security group for web tier
    rules: []
    rules_egress: []

- name: '{{ domain }} - Destroy Web Tier Security Group'
  ec2_group:
    region: '{{ region }}'
    vpc_id: '{{ vpd.vpc_id }}'
    name: '{{ domain_tag }}-sg-web'
    description: security group for web tier
    state: absent

- name: '{{ domain }} - Create empty Security Group for NAT'
  ec2_group:
    region: '{{ region }}'
    vpc_id: '{{ vpd.vpc_id }}'
    name: '{{ domain_tag }}-sg-nat'
    description: security group for NAT
    rules: []
    rules_egress: []

- name: '{{ domain }} - Destroy NAT Security Group'
  ec2_group:
    region: '{{ region }}'
    vpc_id: '{{ vpd.vpc_id }}'
    name: '{{ domain_tag }}-sg-nat'
    description: security group for NAT
    state: absent

# NOTE Elements managed by this playbook, e.g. instances, NATs, etc must be removed first or the delete will fail until those dependencies are removed.
- name: '{{ domain }} - Destroy VPC'
  ec2_vpc:
    resource_tags: '{{ vpc_resource_tags }}'
    region: '{{ region }}'
    vpc_id: '{{ vpd.vpc_id }}'
    state: absent
    wait: yes
