---
- name: Ensure directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ k8s_kubectl_kube_dir }}'
    - '{{ k8s_kubectl_minikube_dir }}'

- name: Copy kubectl config from cluster_host to master
  command: 'scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ k8s_kubectl_cluster_host }}:{{ k8s_kubectl_kube_dir }}/config .'
  args:
    chdir: '{{ k8s_kubectl_kube_dir }}'
    # creates: '{{ k8s_kubectl_kube_dir }}/config'

- name: Copy minikube certs from cluster_host to master
  command: 'scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ k8s_kubectl_cluster_host }}:{{ k8s_kubectl_minikube_dir }}/{{ item }} .'
  args:
    chdir: '{{ k8s_kubectl_minikube_dir }}'
    creates: '{{ k8s_kubectl_minikube_dir }}/{{ item }}'
  with_items:
    - ca.crt
    - client.crt
    - client.key
