---
- name: Install Debian packages
  apt:
    name: '{{ item }}'
    state: present
  become: yes
  with_items:
    - redis-server
    - rlwrap
  when: ansible_distribution == 'Debian'

- name: Insert aliases
  blockinfile:
    create: yes
    dest: ~/.zsh.after/aliases.zsh
    marker: '# {mark} ANSIBLE MANAGED BLOCK (redis)'
    block: |
      alias redis-cli='rlwrap -a -- redis-cli'
