---
- name: Install Debian packages
  apt:
    name: '{{ package }}'
    state: present
  become: yes
  with_items:
    - redis-server
    - rlwrap
  loop_control:
    loop_var: package
  when: ansible_distribution == 'Debian'

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: redis
    aliases_block: |
      alias redis-cli='rlwrap -a -- redis-cli'
