# NOTE: not in use right now
---
- include_vars:
    file: '{{ credentials_file }}'
    name: credentials

- set_fact:
    git_keys: '{{ credentials.git[git_provider] }}'

### git creds
- name: Write git user info to ~/.gitconfig.user
  template:
    src: gitconfig.user.j2
    dest: '{{ git_creds_file }}'
