---
# Options:
# update: yes; when update is yes then the repo will be refreshed
# version: a specific branch to checkout; default is HEAD
# - debug: var=properties

- name: Ensure target directory exists
  file:
    dest: '{{ item.dir | default(properties.dir) }}'
    state: directory
  with_items: '{{ properties.repos }}'

- name: Checkout git repository
  git:
    repo: '{{ item.account }}/{{ item.repo | default(item.name) }}.git'
    dest: '{{ item.dir | default(properties.dir) }}/{{ item.name }}'
    accept_hostkey: yes
    update: no #"{{ item.update | default(0) }}"
    version: "{{ item.branch | default('HEAD') }}"
  with_items: '{{ properties.repos }}'
