---
# NOTE: This fact is required otherwise the git loop fails to find the variable
- set_fact:
    source_directory: '{{ proj.group.source_directory }}'

- debug: var=source_directory

- name: Checkout/Update repository
  # git: repo=git@github.com:{{ project.github.account }}/{{ item.repo|default(item.name) }}.git
  git: repo={{ project.git.account }}/{{ item.repo|default(item.name) }}.git
       dest={{ source_directory }}/{{ item.name }}
       accept_hostkey=yes
       update=no
# TODO: Fix for Her but problem with 'master'
       # version={{ item.version|default() }}
  with_items: '{{ proj.group.projects }}'
  # ignore_errors: yes
