---
- name: Insert aliases
  blockinfile:
    create: yes
    dest: '{{ machine.aliases_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (git)'
    block: |
      alias gsu='git submodule update --remote --merge'
  when: machine.shell == 'zsh'
