---
- include_tasks: clone.yml

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: git
    aliases_block: |
      alias gsu='git submodule update --remote --merge'
