---
- debug:
    var: circleci
    verbosity: 1

- name: Follow projects
  uri:
    url: '{{ circleci.base_url }}/project/{{ project.value.vcs_type }}/{{ project.value.account }}/{{ project.value.repository }}/follow?circle-token={{ circleci.token }}'
    method: POST
  with_dict: '{{ circleci.projects }}'
  loop_control:
    loop_var: project
