---
- homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
    - google-chrome
    - dropbox
    - evernote
    - firefox
    - kindle
    - postman
    - skype
    - slack
    - spotify
    - transmission
