---
# - homebrew_tap: tap={{ item }} state=present
#   with_items: '{{ extras.homebrew_taps }}'

- homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - gpg

- homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
    - chrome
    - dropbox
    - evernote
    - firefox
    - kindle
    - postman
    - skype
    - slack
    - spotify
    - transmission
