---
base_spec:
  cluster_host: node1
  kube_dir: '{{ ansible_env.HOME }}/.kube'
  minikube_dir: '{{ ansible_env.HOME }}/.minikube'
  scp: 'scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

spec: '{{ base_spec | combine(role_spec, recursive=True) }}'
