---
# The physical interface enp0s8 is specific to this hardware setup
base_spec:
  # spoof_intf: enp0s8
  # default_gw: IP
  home: '{{ ansible_env.HOME }}'
  kube_config: '{{ ansible_env.HOME }}/.kube/config'

spec: '{{ base_spec | combine(role_spec, recursive=True) }}'

minikube_env:
  MINIKUBE_WANTUPDATENOTIFICATION: false
  MINIKUBE_WANTREPORTERRORPROMPT: false
  MINIKUBE_HOME: '{{ spec.home }}'
  CHANGE_MINIKUBE_NONE_USER: true
  KUBECONFIG: '{{ spec.kube_config }}'
