---
- name: Install Debian packages
  apt:
    name: [python-dev, python-setuptools]
    state: present
    update_cache: yes
    cache_valid_time: 86400
  become: yes

- name: Install pip
  easy_install:
    name: pip
    # state: latest
  become: yes
