---
- name: Build an image and push it to a private repo
  docker_image:
    path: '{{ build_path }}'
    name: '{{ build_name }}'
    tag: '{{ build_tag }}'
    nocache: no
    push: '{{ build_push | default(yes) }}'
