---
- include_role:
    name: prepd-cli/prompt
  vars:
    role_config:
      domain: ''
      owner: ''
      ssh_username: ''
    label: vagrant

- name: 'Install Vagrant on detected OS ({{ ansible_os_family }})'
  include_tasks: '{{ ansible_os_family | lower }}.yml'
  when: false

- name: Install Vagrant plugins
  include_tasks: plugin.yml
  with_items: '{{ vagrant_plugins }}'
  loop_control:
    loop_var: plugin
  when: false

- name: Insert aliases
  include_role:
    name: prepd/aliases
  vars:
    aliases_marker: vagrant
    aliases_block: |
      alias v='vagrant'
      alias vb='vagrant box'
      alias vd='vagrant destroy'
      vh() { vagrant halt "${1:=node0}" }
      # Halt all vagrant machines
      alias vha='vagrant halt'
      vp() { vagrant provision "${1:=node0}" }
      vsh() { vagrant ssh "${1:=node0}" }
      alias vst='vagrant status'
      alias vstg='vagrant global-status'
      vu() { vagrant up "${1:=node0}" }

- name: "Ensure User's .ssh directory exists"
  file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory
    mode: 0755

- name: 'Template config to {{ cli_vars_dir }}/vagrant.yml'
  template:
    src: vagrant.yml.j2
    dest: '{{ cli_vars_dir }}/vagrant.yml'
