---
- name: 'Check if {{ plugin }} plugin is installed'
  shell: 'vagrant plugin list | grep {{ plugin }}'
  register: result
  failed_when: false
  changed_when: false

- name: 'Install {{ plugin }} plugin'
  command: 'vagrant plugin install {{ plugin }}'
  when: result.rc == 1 # plugin is not installed
