---
- name: Install dependencies
  package:
    name: '{{ package }}'
    state: present
  with_items: [socat, net-tools]
  loop_control:
    loop_var: package
  become: yes

- name: 'Install minikube to {{ spec.bin_file }}'
  get_url:
    url: 'https://github.com/kubernetes/minikube/releases/download/v{{ spec.version }}/minikube-{{ spec.arch }}'
    dest: '{{ spec.bin_file }}'
    mode: 0755
  become: yes
