---
- name: Install common and debian specific packages
  apt:
    name: '{{ package }}'
    state: present
    update_cache: yes
    cache_valid_time: '{{ spec.cache_valid_time }}'
  with_items: '{{ spec.packages + spec.dist_packages }}'
  loop_control:
    loop_var: package
  become: yes

- name: Set time zone
  command: 'timedatectl set-timezone {{ spec.time_zone }}'
  when: spec.time_zone is defined
  become: yes

- name: set locale
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  when: false
