---
- include_vars:
    file: '{{ ansible_os_family | lower }}.yml'

# - debug: var=spec

- include_tasks: '{{ ansible_os_family | lower }}.yml'

- name: Set shell mode to vi
  copy:
    src: inputrc
    dest: '{{ ansible_env.HOME }}/.inputrc'
