---
- include_vars:
    file: '{{ ansible_os_family | lower }}.yml'

# - debug: var=spec

- include_tasks: '{{ ansible_os_family | lower }}.yml'

- name: Create a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes

- name: Set shell mode to vi
  copy:
    src: inputrc
    dest: '{{ ansible_env.HOME }}/.inputrc'
